spring:
  application:
    name: MyWishServer

  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:h2:mem:testmywishdb
    driver-class-name: org.h2.Driver
    username: sa
    password: admin

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: y79dGVeRcMgB4BpbMBDACrUBU_oD-hp6T4HlFx21b2M
